source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'DoorFace' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoorFace
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireImage', '~> 3.4'

  target 'DoorFaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoorFaceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
